name: njsscan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan check
    steps:
    - uses: actions/checkout@v1
    - name: njsscan
      id: njsscan
      uses: ajinabraham/njsscan-action@v5
      with:
        args: '. --sarif --output results.sarif || true'
    - name: Upload njsscan report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif

    - name: Send result to webhook
      run: |
        WEBHOOK_URL="https://webhook.site/0c698d8b-619c-4336-9d22-94820b9bafca"
        PAYLOAD="{\"status\":\"$(( ${{steps.njsscan.outcome}} == 'success' ))\",\"result\":\"${{steps.njsscan.outcome}}\"}"
        echo $PAYLOAD
        curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" "$WEBHOOK_URL"
